// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    // Session-mode URL for migrations (Supabase pooler rejects/queues DDL)
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
